# Generated by Django 3.0.6 on 2020-05-24 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.City', verbose_name='City/Municipality'),
        ),
        migrations.AlterField(
            model_name='user',
            name='province',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Province', verbose_name='Province'),
        ),
    ]
